/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package autoelastic;

import java.awt.Cursor;
import java.awt.Desktop;
import java.awt.Dimension;
import java.awt.Rectangle;
import java.awt.Toolkit;
import javax.swing.ImageIcon;

/**
 *
 * @author Vinicius
 */
public class About extends javax.swing.JFrame {

    /**
     * Creates new form Sobre
     */
    public About() {
        initComponents();
        this.centraliza_tela();
        this.jl_email.setCursor(new Cursor(Cursor.HAND_CURSOR));  
        this.jl_site.setCursor(new Cursor(Cursor.HAND_CURSOR));  
        this.setIconImage(new javax.swing.ImageIcon(getClass().getResource("/images/icone64x64.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jlIcone = new javax.swing.JLabel();
        jl_version = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jta_description = new javax.swing.JTextArea();
        jl_name = new javax.swing.JLabel();
        jl_email = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jl_site = new javax.swing.JLabel();

        setTitle("About");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jlIcone.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlIcone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icone64x64.png"))); // NOI18N

        jl_version.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jl_version.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_version.setText("Version 2.2");

        jta_description.setEditable(false);
        jta_description.setBackground(new java.awt.Color(240, 240, 240));
        jta_description.setColumns(20);
        jta_description.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jta_description.setLineWrap(true);
        jta_description.setRows(5);
        jta_description.setText("AutoElastic is an application for managing resources in cloud computing environments. Its main functionality is to provide automatically elasticity of resources. Currently, only the OpenNebula platform is supported.");
        jta_description.setWrapStyleWord(true);
        jta_description.setBorder(null);
        jScrollPane1.setViewportView(jta_description);

        jl_name.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jl_name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_name.setText("Vinicius Facco Rodrigues");

        jl_email.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jl_email.setForeground(new java.awt.Color(0, 0, 255));
        jl_email.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_email.setText("<html><u>vfrodrigues@unisinos.br<u/></html>");
        jl_email.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jl_emailMouseClicked(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Close");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jl_site.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jl_site.setForeground(new java.awt.Color(0, 0, 255));
        jl_site.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_site.setText("<html><u>http://www.autoelastic.com<u/></html>");
        jl_site.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jl_siteMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jlIcone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jl_version, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jl_site, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl_name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jl_email, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jlIcone)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jl_version)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jl_site, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jl_name)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jl_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jl_emailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_emailMouseClicked
        Desktop desk = java.awt.Desktop.getDesktop();       
        try {      
            desk.browse(new java.net.URI("mailto:vfrodrigues@unisinos.br"));      
        } catch (Exception e) {      
            e.printStackTrace();      
        }
        this.jl_email.setForeground(new java.awt.Color(102, 0, 153));
    }//GEN-LAST:event_jl_emailMouseClicked

    private void jl_siteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_siteMouseClicked
        Desktop desk = java.awt.Desktop.getDesktop();       
        try {      
            desk.browse(new java.net.URI("http://www.autoelastic.com"));      
        } catch (Exception e) {      
            e.printStackTrace();      
        }
        this.jl_email.setForeground(new java.awt.Color(102, 0, 153));
    }//GEN-LAST:event_jl_siteMouseClicked
    
    private void centraliza_tela() {
        // Centraliza a janela de abertura no centro do desktop.  
        Dimension screen = Toolkit.getDefaultToolkit().getScreenSize();  
        Rectangle r      = this.getBounds();  
        // Dimensões da janela  
        int widthSplash = r.width ;  
        int heightSplash = r.height;  
        // calculo para encontrar as cooredenadas X e Y para a centralização da janela.  
        int posX = (screen.width / 2) - ( widthSplash / 2 );  
        int posY = (screen.height / 2) - ( heightSplash / 2 );  
        this.setBounds(posX,posY,widthSplash,heightSplash);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(About.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(About.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(About.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(About.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new About().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlIcone;
    private javax.swing.JLabel jl_email;
    private javax.swing.JLabel jl_name;
    private javax.swing.JLabel jl_site;
    private javax.swing.JLabel jl_version;
    private javax.swing.JTextArea jta_description;
    // End of variables declaration//GEN-END:variables
}
